### ISSUE TITLE
directorytree.dll wasn't found. 

### ISSUE THREAD

**Issue by brutalremus** [michael-valdron/directory-tree#9]
Hi dear my friend,
İf you don't mind. Can you share or upload this file. Thank you so much.

**Comment by michael-valdron** [comment]
Hi @brutalremus, currently working on a first official release of this user control. In addition to providing a NuGet release mentioned in issue #3, I will also release a `.dll` file on the GitHub release coming soon.

**Comment by michael-valdron** [comment]
First release entry is now created with packaged `.dll` file, I will now mark this issue as closed.
